# Generated by Django 5.0.7 on 2024-08-13 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kurs_nomi', models.CharField(max_length=100)),
                ('krediti', models.IntegerField()),
                ('tavsifi', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ismi', models.CharField(max_length=100)),
                ('familiyasi', models.CharField(max_length=100)),
                ('tugilgan_sanasi', models.DateField()),
                ('manzili', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bahosi', models.CharField(max_length=3)),
                ('kurs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.course')),
                ('talaba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.student')),
            ],
        ),
    ]
