# Generated by Django 5.0.7 on 2024-08-13 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='kurs_rasmi',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='student',
            name='student_rasmi',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
